/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.90
 * Generated at: 2018-12-14 07:54:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.department;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class department_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>部门列表</title>\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/img/entertainImg/favicon.ico\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/CSS/jqueryui/themes/default/easyui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/CSS/jqueryui/themes/icon.css\">\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/CSS/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/CSS/jquery.easyui.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/CSS/easyui-lang-zh_CN.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/CSS/PublicStyle.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/CSS/DataImport.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/CSS/main.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/CSS/UserManage.css\">\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/CSS/jquery.form.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar es = \"新建\";\r\n");
      out.write("\t//提交action 的url\r\n");
      out.write("\tvar url = \"\";\r\n");
      out.write("\tvar idd = 1;\r\n");
      out.write("\tvar es = \"\";\r\n");
      out.write("\tvar rolelable=\"\";\r\n");
      out.write("\t//返回json对象的长度\r\n");
      out.write("\tfunction getJsonObjLength(jsonObj) {\r\n");
      out.write("\t\tvar Length = 0;\r\n");
      out.write("\t\tfor ( var item in jsonObj) {\r\n");
      out.write("\t\t\tLength++;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn Length;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t//格式化json\r\n");
      out.write("\tfunction formatJson(json) {\r\n");
      out.write("\t\tvar jsobj = eval(json);\r\n");
      out.write("\t\treturn '{\"total\":' + jsobj.bingdings.length + ',\"rows\":' + json + \"}\";\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t// js格式化Date方法\r\n");
      out.write("\t\r\n");
      out.write("\tDate.prototype.Format = function (fmt) { //author: meizz \r\n");
      out.write("\t    var o = { \r\n");
      out.write("\t        \"M+\": this.getMonth() + 1, //月份 \r\n");
      out.write("\t        \"d+\": this.getDate(), //日 \r\n");
      out.write("\t        \"h+\": this.getHours(), //小时 \r\n");
      out.write("\t        \"m+\": this.getMinutes(), //分 \r\n");
      out.write("\t        \"s+\": this.getSeconds(), //秒 \r\n");
      out.write("\t        \"q+\": Math.floor((this.getMonth() + 3) / 3), //季度 \r\n");
      out.write("\t        \"S\": this.getMilliseconds() //毫秒 \r\n");
      out.write("\t    };\r\n");
      out.write("\t    if (/(y+)/.test(fmt)) fmt = fmt.replace(RegExp.$1, (this.getFullYear() + \"\").substr(4 - RegExp.$1.length));\r\n");
      out.write("\t    for (var k in o)\r\n");
      out.write("\t    if (new RegExp(\"(\" + k + \")\").test(fmt)) fmt = fmt.replace(RegExp.$1, (RegExp.$1.length == 1) ? (o[k]) : ((\"00\" + o[k]).substr((\"\" + o[k]).length)));\r\n");
      out.write("\t    return fmt;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction loadGrid(url,data){\r\n");
      out.write("\t\t//汉化 datagrid 翻页\r\n");
      out.write("\t\t$(\"#llbinfo\").datagrid({\r\n");
      out.write("\t\t\turl : url,\r\n");
      out.write("\t\t\tmethod : 'post',\r\n");
      out.write("\t\t\tqueryParams:data,\r\n");
      out.write("\t\t\tpageSize : 20,\r\n");
      out.write("\t\t\trownumbers : true,\r\n");
      out.write("\t\t\tsingleSelect : true,\r\n");
      out.write("\t\t\tpagination : true,\r\n");
      out.write("\t\t\ttoolbar : [  {\r\n");
      out.write("\t\t\t\ttext : '添加',\r\n");
      out.write("\t\t\t\ticonCls : 'icon-add',\r\n");
      out.write("\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\tadd();\r\n");
      out.write("\t\t\t\t}},'-',{\r\n");
      out.write("\t\t\t\ttext : '修改',\r\n");
      out.write("\t\t\t\ticonCls : 'icon-edit',\r\n");
      out.write("\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\tedit();\r\n");
      out.write("\t\t\t\t}},'-',{\r\n");
      out.write("\t\t\t\t\ttext : '删除',\r\n");
      out.write("\t\t\t\t\ticonCls : 'icon-remove',\r\n");
      out.write("\t\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\t\tdeleteDepartment();\r\n");
      out.write("\t\t\t\t}},'-',{\r\n");
      out.write("\t\t\t\ttext : '名称：<input type=\"text\" id=\"title\"/>',\r\n");
      out.write("\t\t\t\t},'-',{\r\n");
      out.write("\t\t\t\ttext : '查询',\r\n");
      out.write("\t\t\t\ticonCls : 'icon-search',\r\n");
      out.write("\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\tsearchDepartment();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}],\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tonLoadSuccess:function(data){  \r\n");
      out.write("\t\t\t\t $('.preScan').linkbutton({text:'修改角色',plain:true,iconCls:'icon-edit'});\r\n");
      out.write("\t\t\t\t $('.preScan2').linkbutton({text:'选择抄送部门',plain:true,iconCls:'icon-edit'});\r\n");
      out.write("\t\t\t\t $('.preScan1').linkbutton({text:'查看角色',plain:true,iconCls:'icon-search'}); \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tvar pager = $('#llbinfo').datagrid().datagrid('getPager');\r\n");
      out.write("\t\tpager.pagination({\r\n");
      out.write("\t\t\tbeforePageText : \"转到\",\r\n");
      out.write("\t\t\tafterPageText : \"共{pages}页\",\r\n");
      out.write("\t\t\tdisplayMsg : '当前显示从{from}到{to}  共{total}记录',\r\n");
      out.write("\t\t\tonBeforeRefresh : function(pageNumber, pageSize) {\r\n");
      out.write("\t\t\t\t$(this).pagination('loading');\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$(this).pagination('loaded');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t//查看部门的所有角色\r\n");
      out.write("\t function viewRole(value,row,index){\r\n");
      out.write("\t\treturn '<a class=\"preScan1\" href=\"#\" iconCls=\"icon-save\" onclick=\"viewRoles('+ row.id +')\">查看</a>';\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction viewRoles(departmentid){\r\n");
      out.write("\t\trolelable = \"查看\";\r\n");
      out.write("\t\t $('#role').dialog('open').dialog('setTitle',rolelable);\r\n");
      out.write("\t\t $('#editRole').hide();\r\n");
      out.write("\t\t//加载所有角色\r\n");
      out.write("\t\t $(\"#llbinfo1\").datagrid({\r\n");
      out.write("\t\t \tidField : 'id',\r\n");
      out.write("\t\t\turl:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/role/getAllRoleByDepartId.action?departmentid=\"+departmentid,\r\n");
      out.write("\t\t\tmethod : 'post',\r\n");
      out.write("\t\t\trownumbers : true,\r\n");
      out.write("\t\t\tsingleSelect : false,\r\n");
      out.write("\t\t\tonLoadSuccess:function(data){\r\n");
      out.write("\t\t\t\t$('#llbinfo1').datagrid('selectAll');\r\n");
      out.write("\t\t\t\t} \r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t//给部门分配角色\r\n");
      out.write("\t function editRole(value,row,index){\r\n");
      out.write("\t\treturn '<a class=\"preScan\" href=\"#\" iconCls=\"icon-save\" onclick=\"editRoles('+ row.id +')\">查看</a>';\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction editRoles(departmentid){\r\n");
      out.write("\t\trolelable = \"修改\";\r\n");
      out.write("\t\t $('#role').dialog('open').dialog('setTitle',rolelable);\r\n");
      out.write("\t\t $('#editRole').show();\r\n");
      out.write("\t\t $('#llbinfo1').datagrid('unselectAll');\r\n");
      out.write("\t\t//加载所有角色\r\n");
      out.write("\t\t $(\"#llbinfo1\").datagrid({\r\n");
      out.write("\t\t \tidField : 'id',\r\n");
      out.write("\t\t\turl:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/role/getAllRole.action\",\r\n");
      out.write("\t\t\tmethod : 'post',\r\n");
      out.write("\t\t\trownumbers : true,\r\n");
      out.write("\t\t\tsingleSelect : false,\r\n");
      out.write("\t\t\tonLoadSuccess:function(data){\r\n");
      out.write("\t\t\t\t$.post(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/role/getRoleByDepartmentId?departmentid=\"+departmentid,null, function(result) {\r\n");
      out.write("\t\t\t             var funId = result.split(',');\r\n");
      out.write("\t\t\t             var rowData = data.rows;\r\n");
      out.write("\t\t\t\t\t\t    $.each(rowData, function (idx, val) {\r\n");
      out.write("\t\t\t\t\t\t    \tfor(var i=0;i<funId.length;i++){\r\n");
      out.write("\t\t\t\t\t\t    \t\tif (val.id==funId[i]) {\r\n");
      out.write("\t\t\t\t\t\t\t            $(\"#llbinfo1\").datagrid(\"selectRow\", idx);\r\n");
      out.write("\t\t\t\t\t\t\t        }\r\n");
      out.write("\t\t\t\t\t\t    \t}\r\n");
      out.write("\t\t\t\t\t\t    }); \r\n");
      out.write("\t                    \r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t} \r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t//选择抄送部门\r\n");
      out.write("\t function copyDepart(value,row,index){\r\n");
      out.write("\t\treturn '<a class=\"preScan2\" href=\"#\" iconCls=\"icon-save\" onclick=\"copyDeparts('+ row.id +')\">选择</a>';\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction copyDeparts(departmentId){\r\n");
      out.write("\t\trolelable = \"查看\";\r\n");
      out.write("\t\t $('#copy').dialog('open').dialog('setTitle',rolelable);\r\n");
      out.write("\t\t $('#selectDepart').show();\r\n");
      out.write("\t\t $('#llbinfo2').datagrid('unselectAll');\r\n");
      out.write("\t\t//加载所有角色\r\n");
      out.write("\t\t $(\"#llbinfo2\").datagrid({\r\n");
      out.write("\t\t \tidField : 'id',\r\n");
      out.write("\t\t\turl:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/department/getAllAvalibleDepart.action\",\r\n");
      out.write("\t\t\tmethod : 'post',\r\n");
      out.write("\t\t\trownumbers : true,\r\n");
      out.write("\t\t\tsingleSelect : false,\r\n");
      out.write("\t\t\tonLoadSuccess:function(data){\r\n");
      out.write("\t\t\t$.post(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/department/getAlldepartByDId?departmentid=\"+departmentId,null, function(result) {\r\n");
      out.write("\t\t             var funId = result.split(',');\r\n");
      out.write("\t\t             var rowData = data.rows;\r\n");
      out.write("\t\t\t\t\t    $.each(rowData, function (idx, val) {\r\n");
      out.write("\t\t\t\t\t    \tfor(var i=0;i<funId.length;i++){\r\n");
      out.write("\t\t\t\t\t    \t\tif (val.id==funId[i]) {\r\n");
      out.write("\t\t\t\t\t\t            $(\"#llbinfo2\").datagrid(\"selectRow\", idx);\r\n");
      out.write("\t\t\t\t\t\t        }\r\n");
      out.write("\t\t\t\t\t    \t}\r\n");
      out.write("\t\t\t\t\t    }); \r\n");
      out.write("                    \r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t} \r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\tloadGrid('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/department/getAllDepartmentByPage',null);\r\n");
      out.write("\t\t// 确认按钮\r\n");
      out.write("\t\t$(\"#btn_ok\").click(function(){\r\n");
      out.write("\t\t\t\tvar departmentname = $(\"#departmentname\").textbox(\"getText\");\r\n");
      out.write("        \t    var available=$(\"#available\").val();\r\n");
      out.write("\t\t\tif(es==\"添加\"){\r\n");
      out.write("\t\t\t\tvar param = {departmentname:departmentname,available:available};\r\n");
      out.write("\t\t\t\t$.post(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/department/insertDepartment\",param, function(result) {\r\n");
      out.write("\t\t\t\t\t$(\"#dlg\").dialog(\"close\");\r\n");
      out.write("\t\t\t\t\t$('#llbinfo').datagrid('reload');\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tvar row = $('#llbinfo').datagrid('getSelected');\r\n");
      out.write("\t\t\t\tvar param = {id:row.id,departmentname:departmentname,available:available};\r\n");
      out.write("\t\t\t\t$.post(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/department/updateDepartment\",param, function(result) {\r\n");
      out.write("\t\t\t\t\t$(\"#dlg\").dialog(\"close\");\r\n");
      out.write("\t\t\t\t\t$('#llbinfo').datagrid('reload');\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t// 取消按钮\r\n");
      out.write("\t\t$(\"#btn_cancel\").click(function() {\r\n");
      out.write("\t\t\t$('#dlg').dialog('close')\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t// 上传取消按钮\r\n");
      out.write("\t\t$(\"#uploadFileCancel\").click(function() {\r\n");
      out.write("\t\t\tdocument.getElementById('fileImport').value = null;\r\n");
      out.write("\t\t\t$('#import-excel').window('close')\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//分配角色\r\n");
      out.write("\t\t$(\"#save_ok\").click(function(){\r\n");
      out.write("\t\t\tvar departmentid = $('#llbinfo').datagrid('getSelected').id;\r\n");
      out.write("\t\t\tvar roleids = \"\";\r\n");
      out.write("\t\t\tvar rows = $('#llbinfo1').datagrid('getSelections');  \r\n");
      out.write("\t\t\tfor(var i=0; i<rows.length; i++){  \r\n");
      out.write("\t\t\t    if(i==rows.length-1){\r\n");
      out.write("\t\t\t    \troleids += rows[i].id;\r\n");
      out.write("\t\t\t    }else{\r\n");
      out.write("\t\t\t    \troleids += rows[i].id+\",\";\r\n");
      out.write("\t\t\t    }\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(roleids!=\"\"){\r\n");
      out.write("\t\t\t\t$.post('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/department/updateMiddleDepartment',{roleids:roleids,departmentid:departmentid},function(result){\r\n");
      out.write("\t\t\t\t\tif (result==\"1\"){\r\n");
      out.write("\t\t                $('#dlg1').dialog('close');        // close the dialog\r\n");
      out.write("\t\t                $('#llbinfo1').datagrid('reload');    // reload the user data\r\n");
      out.write("\t\t                $.messager.show({\r\n");
      out.write("\t\t                    title: 'Message',\r\n");
      out.write("\t\t                    msg: '操作成功!'\r\n");
      out.write("\t\t                });\r\n");
      out.write("\t\t            } else {\r\n");
      out.write("\t\t                $.messager.show({\r\n");
      out.write("\t\t                    title: 'Error',\r\n");
      out.write("\t\t                    msg: '操作失败!'\r\n");
      out.write("\t\t                });\r\n");
      out.write("\t\t            }\r\n");
      out.write("\t            },'text');\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t$.messager.show({\r\n");
      out.write("\t                title: 'Message',\r\n");
      out.write("\t                msg: '请选择!'\r\n");
      out.write("\t            });\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//选择抄送部门\r\n");
      out.write("\t\t//分配角色\r\n");
      out.write("\t\t$(\"#select_ok\").click(function(){\r\n");
      out.write("\t\t\tvar departmentid = null;\r\n");
      out.write("\t\t\tif($('#llbinfo').datagrid('getSelected')!=null){\r\n");
      out.write("\t\t\t\tdepartmentid = $('#llbinfo').datagrid('getSelected').id;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tvar departmentIds = \"\";\r\n");
      out.write("\t\t\tvar rows = $('#llbinfo2').datagrid('getSelections');  \r\n");
      out.write("\t\t\tfor(var i=0; i<rows.length; i++){  \r\n");
      out.write("\t\t\t    if(i==rows.length-1){\r\n");
      out.write("\t\t\t    \tdepartmentIds += rows[i].id;\r\n");
      out.write("\t\t\t    }else{\r\n");
      out.write("\t\t\t    \tdepartmentIds += rows[i].id+\",\";\r\n");
      out.write("\t\t\t    }\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(departmentIds!=\"\"){\r\n");
      out.write("\t\t\t\t$.post('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/department/updateCopyDepartment',{departmentIds:departmentIds,departmentid:departmentid},function(result){\r\n");
      out.write("\t\t\t\t\tif (result==\"1\"){\r\n");
      out.write("\t\t                $('#copy').dialog('close');        // close the dialog\r\n");
      out.write("\t\t                $('#llbinfo2').datagrid('reload');    // reload the user data\r\n");
      out.write("\t\t                $.messager.show({\r\n");
      out.write("\t\t                    title: 'Message',\r\n");
      out.write("\t\t                    msg: '操作成功!'\r\n");
      out.write("\t\t                });\r\n");
      out.write("\t\t            } else {\r\n");
      out.write("\t\t                $.messager.show({\r\n");
      out.write("\t\t                    title: 'Error',\r\n");
      out.write("\t\t                    msg: '操作失败!'\r\n");
      out.write("\t\t                });\r\n");
      out.write("\t\t            }\r\n");
      out.write("\t            },'text');\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t$.messager.show({\r\n");
      out.write("\t                title: 'Message',\r\n");
      out.write("\t                msg: '请选择!'\r\n");
      out.write("\t            });\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t})\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction fixWidth(percent) {\r\n");
      out.write("\t\treturn ($(\".mdiv\").width() - 30) * percent;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction edit(){\r\n");
      out.write("\t\tes = \"修改\";\r\n");
      out.write("\t\tvar row = $('#llbinfo').datagrid('getSelected');\r\n");
      out.write("\t\tif (row){\r\n");
      out.write("\t\t\t $('#dlg').dialog('open').dialog('setTitle',es);\r\n");
      out.write("\t\t     $('#fm').form('clear');\r\n");
      out.write("\t\t    $(\"#departmentname\").textbox(\"setText\",row.departmentname);\r\n");
      out.write("\t\t\t$(\"#available\").val(row.available);\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t    \talert(\"请选择要修改的数据！\");\r\n");
      out.write("\t    }\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction add(){\r\n");
      out.write("\t\t es = \"添加\";\r\n");
      out.write("\t\t $('#dlg').dialog('open').dialog('setTitle',es);\r\n");
      out.write("\t     $('#fm').form('clear');\r\n");
      out.write("\t     $(\"#available\").val(\"0\");\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction deleteDepartment(){\r\n");
      out.write("\t\tes = \"删除\";\r\n");
      out.write("\t\tvar row = $('#llbinfo').datagrid('getSelected');\r\n");
      out.write("\t\tif (row){\r\n");
      out.write("\t\t\tvar param = {id:row.id};\r\n");
      out.write("\t\t\t$.post(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/department/deleteDepartment\",param, function(result) {\r\n");
      out.write("\t\t\t\t$(\"#dlg\").dialog(\"close\");\r\n");
      out.write("\t\t\t\t$('#llbinfo').datagrid('reload');\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\talert(\"请选择要删除的数据！\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction searchDepartment(){\r\n");
      out.write("\t\tes = \"查询\";\r\n");
      out.write("\t\tvar param = {title:$(\"#title\").val()};\r\n");
      out.write("\t\tloadGrid('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/department/searchDepartment',param);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\t<!-- 部门编辑表 -->\r\n");
      out.write("\t<div id=\"dlg\" class=\"easyui-dialog\" style=\"width:400px;height:200px;padding:0px 0px;\"closed=\"true\" buttons=\"#dlg-buttons\">\r\n");
      out.write("        <!--<div>用户编辑</div>  -->\r\n");
      out.write("        <form id=\"fm\" method=\"post\">\r\n");
      out.write("       <div style=\"text-align:center;\">\r\n");
      out.write("        \t\t<table style=\"margin:auto;\" cellspacing=\"10\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><label>部门名称</label></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input id=\"departmentname\" class=\"easyui-textbox\" style=\"width: 220px;\"></input></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><label>是否可用</label></td>\r\n");
      out.write("\t\t\t\t\t\t<td><select id=\"available\" style=\"width: 220px;\"><option value=\"0\" selected>否</option><option value=\"1\">是</option></select></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("        \t\t</table>\r\n");
      out.write("        \t</div>\r\n");
      out.write("  \t\t\t<div style=\"text-align:center;bottom:15px;margin-top:20px;\">\r\n");
      out.write("        \t\t<a href=\"#\" id=\"btn_ok\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-save'\" style=\"width:20%;\">确定</a>\r\n");
      out.write("\t\t\t\t<a href=\"#\" id=\"btn_cancel\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-cancel'\" style=\"width:20%;\">取消</a>\r\n");
      out.write("        \t</div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("<!--     角色编辑表 -->\r\n");
      out.write("    <div id=\"role\" class=\"easyui-dialog\" style=\"width:30%;height:500px;padding:0px 0px;\"closed=\"true\" buttons=\"#dlg-buttons\">\r\n");
      out.write("        <table id=\"llbinfo1\" class=\"easyui-datagrid\" title=\"角色列表\"\r\n");
      out.write("\t\t\tstyle=\"width: auto; height:90%;\">\r\n");
      out.write("\t\t\t<thead>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th field=\"id\" checkbox=\"true\" id=\"all\"></th>\r\n");
      out.write("\t\t\t\t\t<th\r\n");
      out.write("\t\t\t\t\t\tdata-options=\"field:'rolename',width:fixWidth(0.25),align:'left'\">角色名称</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t\t<div style=\"text-align: center; margin-top: 10px; display:none\" id=\"editRole\">\r\n");
      out.write("\t\t\t\t<a href=\"#\" id=\"save_ok\" class=\"easyui-linkbutton\"\r\n");
      out.write("\t\t\t\t\tdata-options=\"iconCls:'icon-save'\" style=\"width: 20%;\">保存</a> \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("    </div>\r\n");
      out.write("<!--     选择抄送单位 -->\r\n");
      out.write("   <div id=\"copy\" class=\"easyui-dialog\" style=\"width:30%;height:500px;padding:0px 0px;\"closed=\"true\" buttons=\"#dlg-buttons\">\r\n");
      out.write("        <table id=\"llbinfo2\" class=\"easyui-datagrid\" title=\"部门列表\"\r\n");
      out.write("\t\t\tstyle=\"width: auto; height:90%;\">\r\n");
      out.write("\t\t\t<thead>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th field=\"id\" checkbox=\"true\" id=\"allDepart\"></th>\r\n");
      out.write("\t\t\t\t\t<th\r\n");
      out.write("\t\t\t\t\t\tdata-options=\"field:'departmentname',width:fixWidth(0.25),align:'left'\">部门名称</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t\t<div style=\"text-align: center; margin-top: 10px; display:none\" id=\"selectDepart\">\r\n");
      out.write("\t\t\t\t<a href=\"#\" id=\"select_ok\" class=\"easyui-linkbutton\"\r\n");
      out.write("\t\t\t\t\tdata-options=\"iconCls:'icon-save'\" style=\"width: 20%;\">确定</a> \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("    </div>\r\n");
      out.write("\t<div class=\"mdiv\" style=\"width:100%;height:100%;\">\r\n");
      out.write("\t\t<table id=\"llbinfo\" class=\"easyui-datagrid\"  title=\"部门信息\"\r\n");
      out.write("\t\t\tstyle=\"width: auto; height:100%;\">\r\n");
      out.write("\t\t\t<thead>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th\r\n");
      out.write("\t\t\t\t\t\tdata-options=\"field:'id',width:fixWidth(0.1),align:'center'\" hidden=\"true\">编号</th>\r\n");
      out.write("\t\t\t\t\t<th\r\n");
      out.write("\t\t\t\t\t\tdata-options=\"field:'departmentname',width:fixWidth(0.3),align:'center'\">部门名称</th>\r\n");
      out.write("\t\t\t\t \t<th\r\n");
      out.write("\t\t\t\t\t\tdata-options=\"field:'showAvailable',width:fixWidth(0.1),align:'center'\">是否可用</th>\r\n");
      out.write("\t\t\t\t\t<th\r\n");
      out.write("\t\t\t\t\t    data-options=\"field:'forShowRole',width:fixWidth(0.2),formatter:viewRole,align:'center'\">查看</th>\r\n");
      out.write("\t\t\t\t    <th\r\n");
      out.write("\t\t\t\t\t    data-options=\"field:'foreditRole',width:fixWidth(0.2),formatter:editRole,align:'center'\">操作</th>\r\n");
      out.write("\t\t\t\t\t<th\r\n");
      out.write("\t\t\t\t\t    data-options=\"field:'forCopyDepart',width:fixWidth(0.2),formatter:copyDepart,align:'center'\">抄送部门</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t</table>  \r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
