/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.90
 * Generated at: 2018-12-14 07:55:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.role;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class role_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>角色列表</title>\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/img/entertainImg/favicon.ico\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/CSS/jqueryui/themes/default/easyui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/CSS/jqueryui/themes/icon.css\">\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/CSS/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/CSS/jquery.easyui.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/CSS/easyui-lang-zh_CN.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/CSS/PublicStyle.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/CSS/DataImport.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/CSS/main.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/CSS/UserManage.css\">\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/CSS/jquery.form.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar es = \"新建\";\r\n");
      out.write("\t//提交action 的url\r\n");
      out.write("\tvar url = \"\";\r\n");
      out.write("\tvar idd = 1;\r\n");
      out.write("\tvar es = \"\";\r\n");
      out.write("\tvar es1=\"\";\r\n");
      out.write("\t//返回json对象的长度\r\n");
      out.write("\tfunction getJsonObjLength(jsonObj) {\r\n");
      out.write("\t\tvar Length = 0;\r\n");
      out.write("\t\tfor ( var item in jsonObj) {\r\n");
      out.write("\t\t\tLength++;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn Length;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t//格式化json\r\n");
      out.write("\tfunction formatJson(json) {\r\n");
      out.write("\t\tvar jsobj = eval(json);\r\n");
      out.write("\t\treturn '{\"total\":' + jsobj.bingdings.length + ',\"rows\":' + json + \"}\";\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t// js格式化Date方法\r\n");
      out.write("\t\r\n");
      out.write("\tDate.prototype.Format = function (fmt) { //author: meizz \r\n");
      out.write("\t    var o = { \r\n");
      out.write("\t        \"M+\": this.getMonth() + 1, //月份 \r\n");
      out.write("\t        \"d+\": this.getDate(), //日 \r\n");
      out.write("\t        \"h+\": this.getHours(), //小时 \r\n");
      out.write("\t        \"m+\": this.getMinutes(), //分 \r\n");
      out.write("\t        \"s+\": this.getSeconds(), //秒 \r\n");
      out.write("\t        \"q+\": Math.floor((this.getMonth() + 3) / 3), //季度 \r\n");
      out.write("\t        \"S\": this.getMilliseconds() //毫秒 \r\n");
      out.write("\t    };\r\n");
      out.write("\t    if (/(y+)/.test(fmt)) fmt = fmt.replace(RegExp.$1, (this.getFullYear() + \"\").substr(4 - RegExp.$1.length));\r\n");
      out.write("\t    for (var k in o)\r\n");
      out.write("\t    if (new RegExp(\"(\" + k + \")\").test(fmt)) fmt = fmt.replace(RegExp.$1, (RegExp.$1.length == 1) ? (o[k]) : ((\"00\" + o[k]).substr((\"\" + o[k]).length)));\r\n");
      out.write("\t    return fmt;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction loadGrid(url,data){\r\n");
      out.write("\t\t//汉化 datagrid 翻页\r\n");
      out.write("\t\t$(\"#llbinfo\").datagrid({\r\n");
      out.write("\t\t\turl : url,\r\n");
      out.write("\t\t\tmethod : 'post',\r\n");
      out.write("\t\t\tqueryParams:data,\r\n");
      out.write("\t\t\tpageSize : 20,\r\n");
      out.write("\t\t\trownumbers : true,\r\n");
      out.write("\t\t\tsingleSelect : true,\r\n");
      out.write("\t\t\tpagination : true,\r\n");
      out.write("\t\t\ttoolbar : [  {\r\n");
      out.write("\t\t\t\ttext : '添加',\r\n");
      out.write("\t\t\t\ticonCls : 'icon-add',\r\n");
      out.write("\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\tadd();\r\n");
      out.write("\t\t\t\t}},'-',{\r\n");
      out.write("\t\t\t\ttext : '修改',\r\n");
      out.write("\t\t\t\ticonCls : 'icon-edit',\r\n");
      out.write("\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\tedit();\r\n");
      out.write("\t\t\t\t}},'-',{\r\n");
      out.write("\t\t\t\t\ttext : '删除',\r\n");
      out.write("\t\t\t\t\ticonCls : 'icon-remove',\r\n");
      out.write("\t\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\t\tdeleteRole();\r\n");
      out.write("\t\t\t\t}},'-',{\r\n");
      out.write("\t\t\t\ttext : '名称：<input type=\"text\" id=\"title\"/>',\r\n");
      out.write("\t\t\t\t},'-',{\r\n");
      out.write("\t\t\t\ttext : '查询',\r\n");
      out.write("\t\t\t\ticonCls : 'icon-search',\r\n");
      out.write("\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\tsearchRole();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}],\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tonLoadSuccess:function(data){  \r\n");
      out.write("\t\t\t\t $('.preScan').linkbutton({text:'分配权限',plain:true,iconCls:'icon-search'}); \r\n");
      out.write("\t\t\t\t $('.preScan2').linkbutton({text:'分配流程',plain:true,iconCls:'icon-search'}); \r\n");
      out.write("\t\t\t\t $('.preScan1').linkbutton({text:'凭证号登记',plain:true,iconCls:'icon-save'}); \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tvar pager = $('#llbinfo').datagrid().datagrid('getPager');\r\n");
      out.write("\t\tpager.pagination({\r\n");
      out.write("\t\t\tbeforePageText : \"转到\",\r\n");
      out.write("\t\t\tafterPageText : \"共{pages}页\",\r\n");
      out.write("\t\t\tdisplayMsg : '当前显示从{from}到{to}  共{total}记录',\r\n");
      out.write("\t\t\tonBeforeRefresh : function(pageNumber, pageSize) {\r\n");
      out.write("\t\t\t\t$(this).pagination('loading');\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$(this).pagination('loaded');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t//分配角色\r\n");
      out.write("\tfunction editPermission(value,row,index){\r\n");
      out.write("\t\treturn '<a class=\"preScan\" href=\"#\" iconCls=\"icon-save\" onclick=\"editPermissions('+ row.id +')\">分配权限</a>';\r\n");
      out.write("\t}\r\n");
      out.write("\t//分配流程\r\n");
      out.write("\tfunction editProcess(value,row,index){\r\n");
      out.write("\t\treturn '<a class=\"preScan2\" href=\"#\" iconCls=\"icon-save\" onclick=\"editProcesses('+ row.id +')\">分配流程</a>';\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction editPermissions(roleid){\r\n");
      out.write("\t\tvar _tree = $('#t1'),\r\n");
      out.write("\t\troots = _tree.tree('getRoots');\r\n");
      out.write("\t\tfor ( var i = 0; i < roots.length; i++) {\r\n");
      out.write("\t\t\tvar node = _tree.tree('find', roots[i].id);\r\n");
      out.write("\t\t\t_tree.tree('uncheck', node.target);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tes1=\"分配\";\r\n");
      out.write("\t\t $('#dlg1').dialog('open').dialog('setTitle',es1);\r\n");
      out.write("\t     $('#fm1').form('clear');\r\n");
      out.write("\t     $(\"#save_ok\").attr(\"name\",roleid); \r\n");
      out.write("\t     $.post(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/permission/getPermissionByRole?roleId=\"+roleid,null, function(result) {\r\n");
      out.write("\t\t\t\t$(\"#dlg\").dialog(\"close\");\r\n");
      out.write("\t\t\t\t$('#llbinfo').datagrid('reload');\r\n");
      out.write("\t\t\t\t $(result).each(function(i, obj){\r\n");
      out.write("                     var n = $(\"#t1\").tree('find',obj);\r\n");
      out.write("                     if(n){\r\n");
      out.write("                         $(\"#t1\").tree('check',n.target);\r\n");
      out.write("                     }\r\n");
      out.write("                 });\r\n");
      out.write("\t\t});\r\n");
      out.write("\t    \r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction editProcesses(roleid){\r\n");
      out.write("\t\tvar _tree = $('#t2'),\r\n");
      out.write("\t\troots = _tree.tree('getRoots');\r\n");
      out.write("\t\tfor ( var i = 0; i < roots.length; i++) {\r\n");
      out.write("\t\t\tvar node = _tree.tree('find', roots[i].id);\r\n");
      out.write("\t\t\t_tree.tree('uncheck', node.target);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tes1=\"分配流程\";\r\n");
      out.write("\t\t $('#dlg2').dialog('open').dialog('setTitle',es1);\r\n");
      out.write("\t     $('#fm2').form('clear');\r\n");
      out.write("\t     $(\"#save_ok1\").attr(\"name\",roleid); \r\n");
      out.write("\t     $.post(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/process/getProcessByRoleId?roleId=\"+roleid,null, function(result) {\r\n");
      out.write("\t\t\t\t$(\"#dlg\").dialog(\"close\");\r\n");
      out.write("\t\t\t\t$('#llbinfo').datagrid('reload');\r\n");
      out.write("\t\t\t\t $(result).each(function(i, obj){\r\n");
      out.write("                     var n = $(\"#t2\").tree('find',obj);\r\n");
      out.write("                     if(n){\r\n");
      out.write("                         $(\"#t2\").tree('check',n.target);\r\n");
      out.write("                     }\r\n");
      out.write("                 });\r\n");
      out.write("\t\t});\r\n");
      out.write("\t    \r\n");
      out.write("\t}\r\n");
      out.write("\tfunction getTree(){\r\n");
      out.write("\t\t$('#t1').tree({\r\n");
      out.write("\t\t\t//发送异步ajax请求，还会携带id的参数\r\n");
      out.write("\t\t\turl:'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/permission/getByNodeType',\r\n");
      out.write("\t\t\tcheckbox: true,\r\n");
      out.write("\t\t\tonContextMenu:function(e,node){\r\n");
      out.write("\t\t\t\t console.log(node);\r\n");
      out.write("\t\t\t\t//禁止浏览器的窗口打开\r\n");
      out.write("\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t//展开所有菜单\r\n");
      out.write("\t\t\tonLoadSuccess : function(node, data) {\r\n");
      out.write("\t\t        if (data) {\r\n");
      out.write("\t\t            $(data).each(function(index, value) {\r\n");
      out.write("\t\t                if (this.state == 'closed') {\r\n");
      out.write("\t\t                    $('#t1').tree('expandAll');\r\n");
      out.write("\t\t                }\r\n");
      out.write("\t\t            });\r\n");
      out.write("\t\t        }\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$('#t2').tree({\r\n");
      out.write("\t\t\t//发送异步ajax请求，还会携带id的参数\r\n");
      out.write("\t\t\turl:'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/process/getByNodeType',\r\n");
      out.write("\t\t\tcheckbox: true,\r\n");
      out.write("\t\t\tonContextMenu:function(e,node){\r\n");
      out.write("\t\t\t\t console.log(node);\r\n");
      out.write("\t\t\t\t//禁止浏览器的窗口打开\r\n");
      out.write("\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t//展开所有菜单\r\n");
      out.write("\t\t\tonLoadSuccess : function(node, data) {\r\n");
      out.write("\t\t        if (data) {\r\n");
      out.write("\t\t            $(data).each(function(index, value) {\r\n");
      out.write("\t\t                if (this.state == 'closed') {\r\n");
      out.write("\t\t                    $('#t2').tree('expandAll');\r\n");
      out.write("\t\t                }\r\n");
      out.write("\t\t            });\r\n");
      out.write("\t\t        }\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\tgetTree();\r\n");
      out.write("\t\tloadGrid('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/role/showAllRole',null);\r\n");
      out.write("\t\t// 确认按钮\r\n");
      out.write("\t\t$(\"#btn_ok\").click(function(){\r\n");
      out.write("\t\t\t\tvar rolename = $(\"#rolename\").textbox(\"getText\");\r\n");
      out.write("        \t    var available=$(\"#avaiable\").val();\r\n");
      out.write("\t\t\tif(es==\"添加\"){\r\n");
      out.write("\t\t\t\tif(available==\"\"){\r\n");
      out.write("\t\t\t\t\talert(\"请确定角色是否可用！\");\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\tvar param = {rolename:rolename,available:available};\r\n");
      out.write("\t\t\t\t\t$.post(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/role/insertRole\",param, function(result) {\r\n");
      out.write("\t\t\t\t\t\t$(\"#dlg\").dialog(\"close\");\r\n");
      out.write("\t\t\t\t\t\t$('#llbinfo').datagrid('reload');\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tvar row = $('#llbinfo').datagrid('getSelected');\r\n");
      out.write("\t\t\t\tvar param = {id:row.id,rolename:rolename,available:available};\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$.post(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/role/updateRole\",param, function(result) {\r\n");
      out.write("\t\t\t\t\t$(\"#dlg\").dialog(\"close\");\r\n");
      out.write("\t\t\t\t\t$('#llbinfo').datagrid('reload');\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t// 取消按钮\r\n");
      out.write("\t\t$(\"#btn_cancel\").click(function() {\r\n");
      out.write("\t\t\t$('#dlg').dialog('close')\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#btn_cancel1\").click(function() {\r\n");
      out.write("\t\t\t$('#dlg1').dialog('close')\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#btn_cancel2\").click(function() {\r\n");
      out.write("\t\t\t$('#dlg2').dialog('close')\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t// 上传取消按钮\r\n");
      out.write("\t\t$(\"#uploadFileCancel\").click(function() {\r\n");
      out.write("\t\t\tdocument.getElementById('fileImport').value = null;\r\n");
      out.write("\t\t\t$('#import-excel').window('close')\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//分配角色\r\n");
      out.write("\t\t$(\"#save_ok\").click(function(){\r\n");
      out.write("\t\t\tvar permissionid = $(\"#t1\").tree(\"getChecked\");;\r\n");
      out.write("\t\t\tvar roleid = this.name;\r\n");
      out.write("\t\t\tvar permissionids=\"\";\r\n");
      out.write("\t\t\tfor(var i=0;i<permissionid.length;i++){\r\n");
      out.write("\t\t\t\tpermissionids+=permissionid[i].id+\",\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$.post(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/role/editMiddlePermission\",{permissionids:permissionids,roleid:roleid}, function(result) {\r\n");
      out.write("\t\t\t\t$(\"#dlg1\").dialog(\"close\");\r\n");
      out.write("\t\t\t});\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//分配流程\r\n");
      out.write("\t\t$(\"#save_ok1\").click(function(){\r\n");
      out.write("\t\t\tvar processid = $(\"#t2\").tree(\"getChecked\");;\r\n");
      out.write("\t\t\tvar roleid = this.name;\r\n");
      out.write("\t\t\tvar processids=\"\";\r\n");
      out.write("\t\t\tfor(var i=0;i<processid.length;i++){\r\n");
      out.write("\t\t\t\tprocessids+=processid[i].id+\",\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$.post(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/role/editMiddleProcess\",{processids:processids,roleid:roleid}, function(result) {\r\n");
      out.write("\t\t\t\t$(\"#dlg2\").dialog(\"close\");\r\n");
      out.write("\t\t\t});\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t})\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction fixWidth(percent) {\r\n");
      out.write("\t\treturn ($(\".mdiv\").width() - 30) * percent;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction edit(){\r\n");
      out.write("\t\tes = \"修改\";\r\n");
      out.write("\t\tvar row = $('#llbinfo').datagrid('getSelected');\r\n");
      out.write("\t\tif (row){\r\n");
      out.write("\t\t\t $('#dlg').dialog('open').dialog('setTitle',es);\r\n");
      out.write("\t\t     $('#fm').form('clear');\r\n");
      out.write("\t\t    $(\"#rolename\").textbox(\"setText\",row.rolename);\r\n");
      out.write("\t\t\t$(\"#avaiable\").val(row.available);\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t    \talert(\"请选择要修改的数据！\");\r\n");
      out.write("\t    }\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction add(){\r\n");
      out.write("\t\t es = \"添加\";\r\n");
      out.write("\t\t $('#dlg').dialog('open').dialog('setTitle',es);\r\n");
      out.write("\t     $('#fm').form('clear');\r\n");
      out.write("\t     $(\"#avaiable\").val(\"1\");\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction deleteRole(){\r\n");
      out.write("\t\tes = \"删除\";\r\n");
      out.write("\t\tvar row = $('#llbinfo').datagrid('getSelected');\r\n");
      out.write("\t\tif (row){\r\n");
      out.write("\t\t\tvar param = {id:row.id};\r\n");
      out.write("\t\t\t$.post(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/role/deleteRole\",param, function(result) {\r\n");
      out.write("\t\t\t\t$(\"#dlg\").dialog(\"close\");\r\n");
      out.write("\t\t\t\t$('#llbinfo').datagrid('reload');\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\talert(\"请选择要删除的数据！\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction searchRole(){\r\n");
      out.write("\t\tes = \"查询\";\r\n");
      out.write("\t\tvar param = {title:$(\"#title\").val()};\r\n");
      out.write("\t\tloadGrid('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/role/searchRole',param);\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\t<!-- 权限编辑表 -->\r\n");
      out.write("\t<div id=\"dlg\" class=\"easyui-dialog\" style=\"width:400px;height:200px;padding:0px 0px;\"closed=\"true\" buttons=\"#dlg-buttons\">\r\n");
      out.write("        <!--<div>用户编辑</div>  -->\r\n");
      out.write("        <form id=\"fm\" method=\"post\">\r\n");
      out.write("       <div style=\"text-align:center;\">\r\n");
      out.write("        \t\t<table style=\"margin:auto;\" cellspacing=\"10\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><label>名称</label></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input id=\"rolename\" class=\"easyui-textbox\" style=\"width: 220px;\"></input></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><label>是否可用</label></td>\r\n");
      out.write("\t\t\t\t\t\t<td><select id=\"avaiable\" style=\"width: 220px;\"><option value=\"1\" selected>是</option><option value=\"0\">否</option></select></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("        \t\t</table>\r\n");
      out.write("        \t</div>\r\n");
      out.write("  \t\t\t<div style=\"text-align:center;bottom:15px;margin-top:20px;\">\r\n");
      out.write("        \t\t<a href=\"#\" id=\"btn_ok\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-save'\" style=\"width:20%;\">确定</a>\r\n");
      out.write("\t\t\t\t<a href=\"#\" id=\"btn_cancel\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-cancel'\" style=\"width:20%;\">取消</a>\r\n");
      out.write("        \t</div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"dlg1\" class=\"easyui-dialog\" style=\"width:400px;height:400px;padding:0px 0px;\"closed=\"true\" buttons=\"#dlg-buttons\">\r\n");
      out.write("        <!--<div>权限编辑</div>  -->\r\n");
      out.write("        <form id=\"fm1\" method=\"post\">\r\n");
      out.write("       <div style=\"text-align:center;\">\r\n");
      out.write("\t\t\t\t\t\t<div style=\"height: 30%;width: 30%;position:absolute;\"><label>权限:</label></div>\r\n");
      out.write("\t\t\t\t\t\t<div style=\"height: 30%;width: 30%;margin-left: 40%\"><ul id=\"t1\" class=\"easyui-tree\"></ul></div>\r\n");
      out.write("        \t</div>\r\n");
      out.write("  \t\t\t<div style=\"text-align:center;bottom:15px;margin-top:20px;\">\r\n");
      out.write("        \t\t<a href=\"#\" id=\"save_ok\" class=\"easyui-linkbutton\" name=\"aa\" data-options=\"iconCls:'icon-save'\" style=\"width:20%;\">确定</a>\r\n");
      out.write("\t\t\t\t<a href=\"#\" id=\"btn_cancel1\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-cancel'\" style=\"width:20%;\">取消</a>\r\n");
      out.write("        \t</div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"dlg2\" class=\"easyui-dialog\" style=\"width:400px;height:400px;padding:0px 0px;\"closed=\"true\" buttons=\"#dlg-buttons\">\r\n");
      out.write("        <!--<div>流程编辑</div>  -->\r\n");
      out.write("        <form id=\"fm2\" method=\"post\">\r\n");
      out.write("       <div style=\"text-align:center;\">\r\n");
      out.write("\t\t\t\t\t\t<div style=\"height: 30%;width: 30%;position:absolute;\"><label>流程:</label></div>\r\n");
      out.write("\t\t\t\t\t\t<div style=\"height: 30%;width: 30%;margin-left: 40%\"><ul id=\"t2\" class=\"easyui-tree\"></ul></div>\r\n");
      out.write("        \t</div>\r\n");
      out.write("  \t\t\t<div style=\"text-align:center;bottom:15px;margin-top:20px;\">\r\n");
      out.write("        \t\t<a href=\"#\" id=\"save_ok1\" class=\"easyui-linkbutton\" name=\"bb\" data-options=\"iconCls:'icon-save'\" style=\"width:20%;\">确定</a>\r\n");
      out.write("\t\t\t\t<a href=\"#\" id=\"btn_cancel2\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-cancel'\" style=\"width:20%;\">取消</a>\r\n");
      out.write("        \t</div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("\t<div class=\"mdiv\" style=\"width:100%;height:100%;\">\r\n");
      out.write("\t\t<table id=\"llbinfo\" class=\"easyui-datagrid\"  title=\"角色信息\"\r\n");
      out.write("\t\t\tstyle=\"width: auto; height:100%;\">\r\n");
      out.write("\t\t\t<thead>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th\r\n");
      out.write("\t\t\t\t\t\tdata-options=\"field:'id',width:fixWidth(0.1),align:'center'\" hidden=\"true\">编号</th>\r\n");
      out.write("\t\t\t\t\t<th\r\n");
      out.write("\t\t\t\t\t\tdata-options=\"field:'rolename',width:fixWidth(0.4),align:'center'\">名称</th>\r\n");
      out.write("\t\t\t\t \t<th\r\n");
      out.write("\t\t\t\t\t\tdata-options=\"field:'showAvailable',width:fixWidth(0.2),align:'center'\">是否可用</th>\r\n");
      out.write("\t\t\t\t<th\r\n");
      out.write("\t\t\t\t\t    data-options=\"field:'foreditPermission',width:fixWidth(0.2),formatter:editPermission,align:'center'\">操作</th>\r\n");
      out.write("\t\t\t\t\t    <th\r\n");
      out.write("\t\t\t\t\t    data-options=\"field:'foreditProcess',width:fixWidth(0.2),formatter:editProcess,align:'center'\">分配流程</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t</table>  \r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
