/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.90
 * Generated at: 2018-12-25 03:14:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class messageNotice_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>微信公告列表</title>\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/img/entertainImg/favicon.ico\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/CSS/jqueryui/themes/default/easyui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/CSS/jqueryui/themes/icon.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/kindeditor/themes/default/default.css\" />\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/CSS/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/CSS/jquery.easyui.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/CSS/easyui-lang-zh_CN.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/kindeditor/kindeditor-all.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/kindeditor/kindeditor-all-min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/kindeditor/lang/zh_CN.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/CSS/PublicStyle.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/CSS/DataImport.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/CSS/main.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/CSS/UserManage.css\">\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/CSS/jquery.form.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar es = \"新建\";\r\n");
      out.write("\t//提交action 的url\r\n");
      out.write("\tvar url = \"\";\r\n");
      out.write("\tvar idd = 1;\r\n");
      out.write("\tvar es = \"\";\r\n");
      out.write("\tvar rolelable=\"\";\r\n");
      out.write("\t//返回json对象的长度\r\n");
      out.write("\tfunction getJsonObjLength(jsonObj) {\r\n");
      out.write("\t\tvar Length = 0;\r\n");
      out.write("\t\tfor ( var item in jsonObj) {\r\n");
      out.write("\t\t\tLength++;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn Length;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t//格式化json\r\n");
      out.write("\tfunction formatJson(json) {\r\n");
      out.write("\t\tvar jsobj = eval(json);\r\n");
      out.write("\t\treturn '{\"total\":' + jsobj.bingdings.length + ',\"rows\":' + json + \"}\";\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t// js格式化Date方法\r\n");
      out.write("\t\r\n");
      out.write("\tDate.prototype.Format = function (fmt) { //author: meizz \r\n");
      out.write("\t    var o = { \r\n");
      out.write("\t        \"M+\": this.getMonth() + 1, //月份 \r\n");
      out.write("\t        \"d+\": this.getDate(), //日 \r\n");
      out.write("\t        \"h+\": this.getHours(), //小时 \r\n");
      out.write("\t        \"m+\": this.getMinutes(), //分 \r\n");
      out.write("\t        \"s+\": this.getSeconds(), //秒 \r\n");
      out.write("\t        \"q+\": Math.floor((this.getMonth() + 3) / 3), //季度 \r\n");
      out.write("\t        \"S\": this.getMilliseconds() //毫秒 \r\n");
      out.write("\t    };\r\n");
      out.write("\t    if (/(y+)/.test(fmt)) fmt = fmt.replace(RegExp.$1, (this.getFullYear() + \"\").substr(4 - RegExp.$1.length));\r\n");
      out.write("\t    for (var k in o)\r\n");
      out.write("\t    if (new RegExp(\"(\" + k + \")\").test(fmt)) fmt = fmt.replace(RegExp.$1, (RegExp.$1.length == 1) ? (o[k]) : ((\"00\" + o[k]).substr((\"\" + o[k]).length)));\r\n");
      out.write("\t    return fmt;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction loadGrid(url,data){\r\n");
      out.write("\t\t//汉化 datagrid 翻页\r\n");
      out.write("\t\t$(\"#llbinfo\").datagrid({\r\n");
      out.write("\t\t\turl : url,\r\n");
      out.write("\t\t\tmethod : 'post',\r\n");
      out.write("\t\t\tqueryParams:data,\r\n");
      out.write("\t\t\tpageSize : 20,\r\n");
      out.write("\t\t\trownumbers : true,\r\n");
      out.write("\t\t\tsingleSelect : true,\r\n");
      out.write("\t\t\tpagination : true,\r\n");
      out.write("\t\t\ttoolbar : [  {\r\n");
      out.write("\t\t\t\ttext : '添加',\r\n");
      out.write("\t\t\t\ticonCls : 'icon-add',\r\n");
      out.write("\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\tadd();\r\n");
      out.write("\t\t\t\t}},'-',{\r\n");
      out.write("\t\t\t\ttext : '修改',\r\n");
      out.write("\t\t\t\ticonCls : 'icon-edit',\r\n");
      out.write("\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\tedit();\r\n");
      out.write("\t\t\t\t}},'-',{\r\n");
      out.write("\t\t\t\t\ttext : '删除',\r\n");
      out.write("\t\t\t\t\ticonCls : 'icon-remove',\r\n");
      out.write("\t\t\t\t\thandler : function() {\r\n");
      out.write("\t\t\t\t\t\tdeleteNotice();\r\n");
      out.write("\t\t\t\t}}\r\n");
      out.write("// \t\t\t\t,'-',{\r\n");
      out.write("// \t\t\t\ttext : '名称：<input type=\"text\" id=\"title\"/>',\r\n");
      out.write("// \t\t\t\t}\r\n");
      out.write("// \t\t\t\t,'-',{\r\n");
      out.write("// \t\t\t\ttext : '查询',\r\n");
      out.write("// \t\t\t\ticonCls : 'icon-search',\r\n");
      out.write("// \t\t\t\thandler : function() {\r\n");
      out.write("// \t\t\t\t\tsearchNotice();\r\n");
      out.write("// \t\t\t\t}\r\n");
      out.write("// \t\t\t}\r\n");
      out.write("\t\t\t],\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tonLoadSuccess:function(data){  \r\n");
      out.write("\t\t\t\t $('.preScan').linkbutton({text:'修改角色',plain:true,iconCls:'icon-edit'}); \r\n");
      out.write("\t\t\t\t $('.preScan1').linkbutton({text:'上传',plain:true,iconCls:'icon-search'}); \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tvar pager = $('#llbinfo').datagrid().datagrid('getPager');\r\n");
      out.write("\t\tpager.pagination({\r\n");
      out.write("\t\t\tbeforePageText : \"转到\",\r\n");
      out.write("\t\t\tafterPageText : \"共{pages}页\",\r\n");
      out.write("\t\t\tdisplayMsg : '当前显示从{from}到{to}  共{total}记录',\r\n");
      out.write("\t\t\tonBeforeRefresh : function(pageNumber, pageSize) {\r\n");
      out.write("\t\t\t\t$(this).pagination('loading');\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$(this).pagination('loaded');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t//介绍富文本编辑器\r\n");
      out.write("    KindEditor.ready(function(K) {\r\n");
      out.write("    \tvar curWwwPath = window.document.location.href;\r\n");
      out.write("    \tvar pathName = window.document.location.pathname;\r\n");
      out.write("        var pos = curWwwPath.indexOf(pathName);\r\n");
      out.write("        //获取主机地址，如： http://localhost:8083\r\n");
      out.write("        var localhostPaht = curWwwPath.substring(0, pos);\r\n");
      out.write("        \r\n");
      out.write("        introEditor = K.create(\"#content\", {\r\n");
      out.write("            width : 100,\r\n");
      out.write("            minHeight : '300px',\r\n");
      out.write("            allowFileManager : true,\r\n");
      out.write("            formatUploadUrl: false,\r\n");
      out.write("            urlType: \"domain\",\r\n");
      out.write("            filePostName:\"uploadFile\",\r\n");
      out.write("            uploadJson : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/notice/upload\",\r\n");
      out.write("          //  fileManagerJson : '../jsp/file_manager_json.jsp',\r\n");
      out.write("            \r\n");
      out.write("            afterUpload: function(url){\r\n");
      out.write("            \t var img = $(\"#postImg\").val();\r\n");
      out.write("                 if (img.length > 0) {\r\n");
      out.write("                     $(\"#postImg\").val(img + \",\" + localhostPaht+url);\r\n");
      out.write("                 } else {\r\n");
      out.write("                     $(\"#postImg\").val(localhostPaht+url);\r\n");
      out.write("                 }\r\n");
      out.write("                 this.sync();\r\n");
      out.write("            }, //图片上传后，将上传内容同步到textarea中\r\n");
      out.write("            afterBlur: function(){this.sync();},   ////失去焦点时，将上传内容同步到textarea中\r\n");
      out.write("            cssData: \".ke-content img {max-width: 200px;height:auto;}\",   //控制图片大小\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            items : [ 'source', '|', 'undo', 'redo', '|', 'preview', 'print',\r\n");
      out.write("                    'template', 'code', 'cut', 'copy', 'paste', 'plainpaste',\r\n");
      out.write("                    'wordpaste', '|', 'justifyleft', 'justifycenter',\r\n");
      out.write("                    'justifyright', 'justifyfull', 'insertorderedlist',\r\n");
      out.write("                    'insertunorderedlist', 'indent', 'outdent', 'subscript',\r\n");
      out.write("                    'superscript', 'clearhtml', 'quickformat', 'selectall',\r\n");
      out.write("                    '|', 'formatblock', 'fontname', 'fontsize', '|',\r\n");
      out.write("                    'forecolor', 'hilitecolor', 'bold', 'italic', 'underline',\r\n");
      out.write("                    'strikethrough', 'lineheight', 'removeformat', '|',\r\n");
      out.write("                    'image', 'flash', 'media', 'insertfile', 'table', 'hr',\r\n");
      out.write("                    'pagebreak', 'anchor', 'link', 'unlink', '|', 'about',\r\n");
      out.write("                    'fullscreen' ],\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\tloadGrid('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/notice/getAllMessageNoticeByPage',null);\r\n");
      out.write("\t\t// 确认按钮\r\n");
      out.write("\t\t$(\"#btn_ok\").click(function(){\r\n");
      out.write("\t\t    var html = introEditor.html(); //获取编辑框内容，匹配img.src\r\n");
      out.write("\t\t\tvar reg = /<img\\b.*?(?:\\>|\\/>)/gi;\r\n");
      out.write("\t\t    var array = html.match(reg);\r\n");
      out.write("\t\t    var regSrc = /\\bsrc\\b\\s*=\\s*[\\'\\\"]?([^\\'\\\"]*)[\\'\\\"]?/i;\r\n");
      out.write("\t\t    var result = new Array();    //编辑框内剩余的图片，需要保存的\r\n");
      out.write("\t\t    for(index in array){\r\n");
      out.write("\t\t    \t//var str = array[index].match(regSrc)[1].split(\"image/\")[1];\r\n");
      out.write("\t\t    \tvar str = array[index].match(regSrc)[1];\r\n");
      out.write("\t\t    \tresult.push(str);\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t    var inputStr = $(\"#postImg\").val().split(\",\");\r\n");
      out.write("\t\t    var merge = result.concat(inputStr).filter(function(v, i, arr) {return arr.indexOf(v) == arr.lastIndexOf(v);});\r\n");
      out.write("\r\n");
      out.write("\t\t    for (x in merge){\r\n");
      out.write("\t\t    \tvar imgUrl = merge[x].split(\"/images/\")[1];\r\n");
      out.write("\t\t    \tvar param = {fileAbsSavePath:imgUrl};\r\n");
      out.write("\t\t    \t//删除图片\r\n");
      out.write("\t\t\t\t$.post(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/notice/deleteFile\",param, function(result) {\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t    //result 转成字符串  放到 hidden 的 input里去\r\n");
      out.write("\t\t    $(\"#postImg\").val(result.join(\",\"));\r\n");
      out.write("\t\t\t\tvar mainTitle = $(\"#mainTitle\").textbox(\"getText\");\r\n");
      out.write("        \t    var contentTitle=$(\"#contentTitle\").textbox(\"getText\");\r\n");
      out.write("        \t    var department=$(\"#department\").textbox(\"getText\");\r\n");
      out.write("        \t    var userName=$(\"#users\").textbox(\"getText\");\r\n");
      out.write("        \t    var content=introEditor.html();\r\n");
      out.write("        \t    var imgUrl = $(\"#postImg\").val();\r\n");
      out.write("\t\t\tif(es==\"添加\"){\r\n");
      out.write("\t\t\t\tvar param = {maintitle:mainTitle,contenttitle:contentTitle,content:content,userName:userName,department:department,imgUrl:imgUrl};\r\n");
      out.write("\t\t\t\t$.post(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/notice/insertMessagenotice\",param, function(result) {\r\n");
      out.write("\t\t\t\t\t$(\"#dlg\").dialog(\"close\");\r\n");
      out.write("\t\t\t\t\t$('#llbinfo').datagrid('reload');\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tvar row = $('#llbinfo').datagrid('getSelected');\r\n");
      out.write("\t\t\t\tvar param = {id:row.id,maintitle:mainTitle,contenttitle:contentTitle,content:content,userName:userName,department:department,imgUrl:imgUrl};\r\n");
      out.write("\t\t\t\t$.post(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/notice/updateMessagenotice\",param, function(result) {\r\n");
      out.write("\t\t\t\t\t$(\"#dlg\").dialog(\"close\");\r\n");
      out.write("\t\t\t\t\t$('#llbinfo').datagrid('reload');\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t// 取消按钮\r\n");
      out.write("\t\t$(\"#btn_cancel\").click(function() {\r\n");
      out.write("\t\t\t$('#dlg').dialog('close')\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#department\").combobox({\r\n");
      out.write("\t\t\tonSelect:function(rec){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar url = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/user/showUsers?departmentname='+rec.departmentname;\r\n");
      out.write("\t\t\t\t$(\"#users\").combobox('reload', url);\r\n");
      out.write("\t\t\t\t$(\"#users\").combobox('setValue', \"\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\r\n");
      out.write("\t})\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction fixWidth(percent) {\r\n");
      out.write("\t\treturn ($(\".mdiv\").width() - 30) * percent;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction edit(){\r\n");
      out.write("\t\tes = \"修改\";\r\n");
      out.write("\t\tvar row = $('#llbinfo').datagrid('getSelected');\r\n");
      out.write("\t\tif (row){\r\n");
      out.write("\t\t\t $('#dlg').dialog('open').dialog('setTitle',es);\r\n");
      out.write("\t\t     $('#fm').form('clear');\r\n");
      out.write("\t\t    $(\"#content\").val(row.content);\r\n");
      out.write("\t\t    introEditor.html(row.content);\r\n");
      out.write("\t\t\t$(\"#mainTitle\").textbox(\"setText\",row.maintitle);\r\n");
      out.write("\t\t\t$(\"#contentTitle\").textbox(\"setText\",row.contenttitle);\r\n");
      out.write("\t\t\t$(\"#users\").textbox(\"setText\",row.userName);\r\n");
      out.write("\t\t\t$(\"#department\").textbox(\"setText\",row.department);\r\n");
      out.write("\t\t\t$(\"#postImg\").val(row.imgUrl);\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t    \talert(\"请选择要修改的数据！\");\r\n");
      out.write("\t    }\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction add(){\r\n");
      out.write("\t\t es = \"添加\";\r\n");
      out.write("\t\t $('#dlg').dialog('open').dialog('setTitle',es);\r\n");
      out.write("\t     $('#fm').form('clear');\r\n");
      out.write("\t     introEditor.html(\"\");\r\n");
      out.write("\t     \r\n");
      out.write("\t     var departmentname = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.departmentname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("';\r\n");
      out.write("\t     var userName = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("';\r\n");
      out.write("\t  \t$(\"#users\").textbox(\"setText\",userName);\r\n");
      out.write("\t  \t$(\"#department\").textbox(\"setText\",departmentname);\r\n");
      out.write("//获取添加的主标题\r\n");
      out.write("// \t     $.post(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/notice/getMainTitle\",param, function(result) {\r\n");
      out.write("// \t\t\t\tif(result!=null){\r\n");
      out.write("// \t\t\t\t\t$(\"#mainTitle\").textbox(\"setText\",result);\r\n");
      out.write("// \t\t\t\t}\r\n");
      out.write("// \t\t });\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction deleteNotice(){\r\n");
      out.write("\t\tes = \"删除\";\r\n");
      out.write("\t\tvar msg = \"您真的确定要删除吗？\\n\\n请确认！\"; \r\n");
      out.write("\t\tif (confirm(msg)==true){ \r\n");
      out.write("\t\t\tvar row = $('#llbinfo').datagrid('getSelected');\r\n");
      out.write("\t\t\tif (row){\r\n");
      out.write("\t\t\t\tvar param = {id:row.id};\r\n");
      out.write("\t\t\t\t$.post(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/notice/deleteMessagenotice\",param, function(result) {\r\n");
      out.write("\t\t\t\t\t$(\"#dlg\").dialog(\"close\");\r\n");
      out.write("\t\t\t\t\t$('#llbinfo').datagrid('reload');\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\talert(\"请选择要删除的数据！\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}else{ \r\n");
      out.write("\t\t\treturn false; \r\n");
      out.write("\t\t} \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction searchNotice(){\r\n");
      out.write("\t\tes = \"查询\";\r\n");
      out.write("\t\tvar param = {title:$(\"#title\").val()};\r\n");
      out.write("\t\tloadGrid('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/notice/searchNotice',param);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\t<!-- 公告编辑表 -->\r\n");
      out.write("\t<div id=\"dlg\" class=\"easyui-dialog\" style=\"width:800px;height:600px;padding:0px 0px;\"closed=\"true\" buttons=\"#dlg-buttons\">\r\n");
      out.write("        <!--<div>用户编辑</div>  -->\r\n");
      out.write("        <form id=\"fm\" method=\"post\">\r\n");
      out.write("       <div style=\"text-align:center;\">\r\n");
      out.write("        \t\t<table style=\"margin:auto;\" cellspacing=\"10\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><label>主标题</label></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input id=\"mainTitle\" class=\"easyui-textbox\" style=\"width: 300px;\"></input></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><label>内容标题</label></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input id=\"contentTitle\" class=\"easyui-textbox\" style=\"width: 300px;\"></input></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><label>所在部门</label></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input id=\"department\" class=\"easyui-combobox\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-options=\"\r\n");
      out.write("\t\t\t\t\t\t\turl:'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/department/getAllDepartment',\r\n");
      out.write("\t\t\t\t\t\t\tmethod:'get',\r\n");
      out.write("\t\t\t\t\t\t\tvalueField:'id',\r\n");
      out.write("\t\t\t\t\t\t\ttextField:'departmentname',\r\n");
      out.write("\t\t\t\t\t\t\teditable:false,\r\n");
      out.write("\t\t\t\t\t\t\tpanelHeight:'200',\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 300px;\"></input></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><label>填写人</label></td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<!-- <input id=\"userName\" class=\"easyui-textbox\" style=\"width: 300px;\"></input> -->\r\n");
      out.write("\t\t\t\t\t\t<input id=\"users\" class=\"easyui-combobox\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-options=\"\r\n");
      out.write("\t\t\t\t\t\t\turl:'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/user/showUsers?departmentname='+'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.departmentname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("',\r\n");
      out.write("\t\t\t\t\t\t\tmethod:'get',\r\n");
      out.write("\t\t\t\t\t\t\tvalueField:'id',\r\n");
      out.write("\t\t\t\t\t\t\ttextField:'username',\r\n");
      out.write("\t\t\t\t\t\t\teditable:true,\r\n");
      out.write("\t\t\t\t\t\t\tpanelHeight:'200'\r\n");
      out.write("\t\t\t\t\t\t\t\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 300px;\"></input></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><label>内容</label></td>\r\n");
      out.write("\t\t\t\t\t\t<td><textarea rows=\"20\" style=\"width:400px;\" id=\"content\" name=\"content\" class=\"easyui-validatebox\" data-options=\"validType:'length[1,1000000]'\" invalidMessage=\"最大长度不能超过1000000\"\"></textarea></td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" id=\"postImg\" name=\"imgUrl\">\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("        \t\t</table>\r\n");
      out.write("        \t</div>\r\n");
      out.write("  \t\t\t<div style=\"text-align:center;bottom:15px;margin-top:20px;\">\r\n");
      out.write("        \t\t<a href=\"#\" id=\"btn_ok\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-save'\" style=\"width:20%;\">确定</a>\r\n");
      out.write("\t\t\t\t<a href=\"#\" id=\"btn_cancel\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-cancel'\" style=\"width:20%;\">取消</a>\r\n");
      out.write("        \t</div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("\t<div class=\"mdiv\" style=\"width:100%;height:100%;\">\r\n");
      out.write("\t\t<table id=\"llbinfo\" class=\"easyui-datagrid\"  title=\"微信公告信息\"\r\n");
      out.write("\t\t\tstyle=\"width: auto; height:100%;\">\r\n");
      out.write("\t\t\t<thead>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th\r\n");
      out.write("\t\t\t\t\t\tdata-options=\"field:'id',width:fixWidth(0.1),align:'center'\" hidden=\"true\">编号</th>\r\n");
      out.write("\t\t\t\t\t<th\r\n");
      out.write("\t\t\t\t\t\tdata-options=\"field:'maintitle',width:fixWidth(0.2),align:'center'\">主标题</th>\r\n");
      out.write("\t\t\t\t \t<th\r\n");
      out.write("\t\t\t\t\t\tdata-options=\"field:'contenttitle',width:fixWidth(0.2),align:'center'\">内容标题</th>\r\n");
      out.write("\t\t\t\t    <th\r\n");
      out.write("\t\t\t\t\t\tdata-options=\"field:'usertime',width:fixWidth(0.2),align:'center'\">开始时间</th>\r\n");
      out.write("\t\t\t\t\t<th\r\n");
      out.write("\t\t\t\t\t\tdata-options=\"field:'department',width:fixWidth(0.2),align:'center'\">所在部门</th>\r\n");
      out.write("\t\t\t\t\t<th\r\n");
      out.write("\t\t\t\t\t\tdata-options=\"field:'userName',width:fixWidth(0.2),align:'center'\">填写人</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t</table>  \r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
